version: 1.0.{build}
pull_requests:
  do_not_increment_build_number: true

image: Visual Studio 2019

platform:
  - x64

configuration:
  - Release

install:
  - docker version

init:
  - cmd: docker --version
  - cmd: msbuild /version

build_script:
  - cmd: docker build . -t texugo