version: 1.0.{build}
pull_requests:
  do_not_increment_build_number: true

image: Visual Studio 2019

platform:
  - x64

configuration:
  - Release

install:
  - choco install xdelta3

init:
  - cmd: cmake --version
  - cmd: msbuild /version

build_script:
  - cmd: cmake -B build
  - cmd: cmake --build build

only_commits:
  files:
    - include/
    - resources/
    - src/
    - tests/
    - appveyor.yml
    - CMakeLists.txt