name: CMake

on:
  push: {}
  pull_request: {}

jobs:
    build:
        runs-on: ubuntu-latest
        steps:

            - name: Checkout repository
              uses: actions/checkout@v2

            - name: Set up cache
              id: cache-cpm
              uses: actions/cache@v2
              with:
                path: ~/cpm-cache
                key: ${{ runner.os }}-cpm-${{ hashFiles('**/') }}
                restore-keys: |
                  ${{ runner.os }}-cpm-

            - name: Install CMake
              run: |
                wget -O cmake.sh https://cmake.org/files/v3.16/cmake-3.16.3-Linux-x86_64.sh 
                sudo sh cmake.sh --skip-license --exclude-subdir --prefix=/usr/local
                export PATH=/usr/local/bin:$PATH
                cmake --version
                
            - name: Install Prometheus dependencies
              run: sudo apt-get install -y zlib1g-dev libcurl4-gnutls-dev
              
            - name: Build
              run: |
                mkdir build && cd build
                cmake -DCPM_SOURCE_CACHE=~/cpm-cache ..
                make -j2

