name: CMake

on:
  push: {}
  pull_request: {}

jobs:
    build:
        runs-on: ubuntu-latest
        steps:

            - name: Checkout repository
              uses: actions/checkout@v2

            - name: Install CMake
              run: |
                wget -O cmake.sh https://cmake.org/files/v3.16/cmake-3.16.0-Linux-x86_64.sh 
                sudo sh cmake.sh --skip-license --exclude-subdir --prefix=/usr/local
                export PATH=/usr/local/bin:$PATH
                cmake --version
              
            - name: Run tests
              run: |
                mkdir build && cd build
                cmake ..
                make -j2
                ctest -R texugo_tests -V -j2
