name: Docker

on:
  push: {}
  pull_request: {}

jobs:
    build:
        runs-on: ubuntu-latest
        steps:

            - name: Checkout repository
              uses: actions/checkout@v2

            - name: Build Image
              run: docker build . -t texugo

            - name: Run Unit Tests
              run: docker run --entrypoint "./texugo_tests" texugo

            - name: Run Functional Tests
              run: |
                pip install robotframework
                cd tests/functional_tests/
                robot -P libraries -d output tests