name: Docker

on:
  push: {}
  pull_request: {}

jobs:
    build:
        runs-on: ubuntu-latest
        strategy:
          matrix:
            python-version: [3.8]

        steps:

            - name: Checkout repository
              uses: actions/checkout@v2

            - name: Build Image
              run: docker build . -t texugo

            - name: Run Unit Tests
              run: docker run --entrypoint "ctest -R texugo_test -V -j2" texugo

            - name: Run Functional Tests
              run: |
                sudo pip install robotframework docker
                cd tests/functional/
                robot -P libraries -d output tests